---
title: "Testing"
>>>>>>> fe9746c (added freedom and esg bank data)
format: html
editor: visual
---

```{r, warning=FALSE}
# import libraries
library(here)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(janitor)
```

```{r}

# read in freedom data
freedom <- read.csv(here('data/freedom/efw_ratings.csv'), header = FALSE)

# set the 5th row as column names
colnames(freedom) <- freedom[5, ]

# remove first 4 rows
freedom <- freedom[-c(1:5), ]

# clean up column names in freedom using janitor package 
freedom <- clean_names(freedom)

# convert appropriate columns from char to num
freedom <- freedom %>%
      mutate(across(6:ncol(freedom), as.numeric))

```

```{r}

# read in esg data
esg_bank <- read.csv(here('data/esg_worldbank.csv'))

# ------------------------------- update column names ------------------------------- #

# extract column names for columns 5 to 29
original_col_names <- colnames(esg_bank)[5:29]

# remove the first 7 characters
modified_col_names <- substr(original_col_names, 10, nchar(original_col_names))

# remove the last character of all of the year columns

# update the data frame with modified column names
colnames(esg_bank)[5:29] <- modified_col_names

# remove 'Country Code' and 'Series Code' columns
esg_bank <- subset(esg_bank, select = -c(Country.Code, Series.Code))

# renaming esg columns
colnames(esg_bank)[colnames(esg_bank) == "Country.Name"] <- "Countries"
colnames(esg_bank)[colnames(esg_bank) == "Series.Name"] <- "Series"

# view the modified column names to confirm changes
colnames(esg_bank)


```

```{r}
esg_2022 <- read.csv(here('data/esg_bank_2022.csv'))
```


```{r}
# ------------------------------- freedom correlation ------------------------------- #
ggplot(freedom, aes(x = economic_freedom_summary_index, y = x3a_money_growth)) +
  geom_point() +  # add points
  theme_minimal() +  # minimal theme for cleaner look
  labs(title = "Relationship between Economic Freedom and Gender Disparity",
       x = "Economic Freedom Summary Index",
       y = "Gender Disparity Index")

```


```{r}
# ------------------------------- lin reg testing ------------------------------- #

```







